### ISSUE TITLE
Plugin update issue

### ISSUE THREAD

**Issue by vxkShelby** [eldoriarpg/BloodNight#214]
Plugin is showing bad update message on login ... in versions ....

04.03 10:22:44 [Server] INFO [BloodNight] New version of BloodNight available.
04.03 10:22:44 [Server] INFO [BloodNight] Newest version: 0.11.2! Current version: 0.11.3!
04.03 10:22:44 [Server] INFO [BloodNight] Download new version here: https://www.spigotmc.org/resources/85095

**Comment by rainbowdashlabs** [comment]
Fixed with #212

**Comment by vxkShelby** [comment]
Fixed thru discord
