### ISSUE TITLE
Config Resets

### ISSUE THREAD

**Issue by nanohard** [eldoriarpg/BloodNight#49]
The config file `BloodNight/worldSettings/world.yml` resets to default whenever I restart my server.
I am not editing the file manually, I am doing it via in-game commands.

The values that are being reset:
- Mob Damage
- Mob Health
- Mob Drop

- Vanilla Mob Damage
- Vanilla Mob Health
- Vanilla Mob Drop

All other settings seem to be persisting, as far as I can tell.
No SQL db being used, just flat files across the board.

EDIT0: confirmed db

**Comment by RainbowDashLabs** [comment]
@nanohard
I was able to reproduce the vanilla settings bug. And the missing health and damage keys.

What specific key do you mean by `Mob Drop`? Can you provide me the full path? I didnt found any issues there

**Comment by nanohard** [comment]
Sorry. I no longer have the files. I think the `multiplier` is what I meant.

**Comment by RainbowDashLabs** [comment]
The whole vanilla settings were not serialized correctly ^^
I would assume that this is fixed ^^
