### ISSUE TITLE
End sound being used as start sound

### ISSUE THREAD

**Issue by lunarpatriots** [eldoriarpg/BloodNight#68]
The plugin uses the configured end sounds to be played instead of the configured start sounds.

https://github.com/eldoriarpg/BloodNight/blob/e2ba9a85c5fc3a18fddac5fc3e7bb79a42260e64/BloodNight-core/src/main/java/de/eldoria/bloodnight/config/worldsettings/sound/SoundSettings.java#L67-L69

**Comment by RainbowDashLabs** [comment]
Well yes.

Gonna change it in the next release ^^ Thanks for noticing :D

**Comment by RainbowDashLabs** [comment]
Fixed in 0.10.6 and Released
